OMS.App/Controllers/Order/OrderModifyController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Text;
using System.Web.Mvc;

using Samsonite.OMS.DTO;
using Samsonite.OMS.Database;
using Samsonite.OMS.Encryption;
using Samsonite.OMS.Service;
using Samsonite.Utility.Common;
using OMS.App.Helper;

namespace OMS.App.Controllers
{
    public class OrderModifyController : BaseController
    {
        //
        // GET: /OrderModify/

        #region 查询
        [UserPowerAuthorize]
        public ActionResult Index()
        {
            //加载语言包
            ViewBag.LanguagePack = this.GetLanguagePack;
            //菜单栏
            ViewBag.MenuBar = this.MenuBar();
            //功能权限
            ViewBag.FunctionPower = this.FunctionPowers();
            //订单号
            ViewBag.OrderID = VariableHelper.SaferequestStr(Request.QueryString["OrderID"]);
            //快速时间选项
            ViewData["quicktime_list"] = QuickTimeHelper.QuickTimeOption();
            //流程状态
            ViewData["proccess_list"] = OrderHelper.ProccessModifyStatusObject();
            //仓库状态
            ViewData["wh_list"] = OrderHelper.WarehouseStatusReflect();

            return View();
        }

        [UserPowerAuthorize(Type = UserPowerAuthorize.ResultType.Json)]
        public JsonResult Index_Message()
        {
            //加载语言包
            var _LanguagePack = this.GetLanguagePack;

            JsonResult _result = new JsonResult();
            List<EntityRepository.SqlQueryCondition> _sqlWhere = new List<EntityRepository.SqlQueryCondition>();
            string _orderid = VariableHelper.SaferequestStr(Request.Form["orderid"]);
            string _time1 = VariableHelper.SaferequestStr(Request.Form["time1"]);
            string _time2 = VariableHelper.SaferequestStr(Request.Form["time2"]);
            string[] _storeid = VariableHelper.SaferequestStringArray(Request.Form["store"]);
            int _process_status = VariableHelper.SaferequestInt(Request.Form["proccess_status"]);
            int _stock_status = VariableHelper.SaferequestInt(Request.Form["stock_status"]);
            using (var db = new ebEntities())
            {
                //搜索条件
                if (!string.IsNullOrEmpty(_orderid))
                {
                    _sqlWhere.Add(new EntityRepository.SqlQueryCondition() { Condition = "((OrderNo like {0}) or (SubOrderNo like {0}))", Param = "%" + _orderid + "%" });
                }

                if (!string.IsNullOrEmpty(_time1))
                {
                    _sqlWhere.Add(new EntityRepository.SqlQueryCondition() { Condition = "datediff(day,AddDate,{0})<=0", Param = VariableHelper.SaferequestTime(_time1) });
                }

                if (!string.IsNullOrEmpty(_time2))
                {
                    _sqlWhere.Add(new EntityRepository.SqlQueryCondition() { Condition = "datediff(day,AddDate,{0})>=0", Param = VariableHelper.SaferequestTime(_time2) });
                }

                //默认显示当前账号允许看到的店铺订单
                var _UserMalls = new List<string>();
                if (_storeid != null)
                {
                    _UserMalls = _storeid.Where(p => this.CurrentLoginUser.UserMalls.Contains(p)).ToList();
                }
                else
                {
                    _UserMalls = this.CurrentLoginUser.UserMalls;
                }
                _sqlWhere.Add(new EntityRepository.SqlQueryCondition() { Condition = "MallSapCode in (select item from strToIntTable('" + string.Join(",", _UserMalls) + "',','))", Param = null });

                if (_process_status > 0)
                {
                    _sqlWhere.Add(new EntityRepository.SqlQueryCondition() { Condition = "Status={0}", Param = _process_status });
                }

                if (_stock_status > 0)
                {
                    switch (_stock_status)
                    {
                        case 1:
                            _sqlWhere.Add(new EntityRepository.SqlQueryCondition() { Condition = "ApiIsRead={0}", Param = 0 });
                            break;
                        case 2:
                            _sqlWhere.Add(new EntityRepository.SqlQueryCondition() { Condition = "ApiIsRead={0}", Param = 1 });
                            _sqlWhere.Add(new EntityRepository.SqlQueryCondition() { Condition = "ApiStatus={0}", Param = (int)WarehouseStatus.DealSuccessful });
                            break;
                        case 3:
                            _sqlWhere.Add(new EntityRepository.SqlQueryCondition() { Condition = "ApiIsRead={0}", Param = 1 });
                            _sqlWhere.Add(new EntityRepository.SqlQueryCondition() { Condition = "ApiStatus={0}", Param = (int)WarehouseStatus.DealFail });
                            break;
                        case 4:
                            _sqlWhere.Add(new EntityRepository.SqlQueryCondition() { Condition = "ApiIsRead={0}", Param = 1 });
                            _sqlWhere.Add(new EntityRepository.SqlQueryCondition() { Condition = "ApiStatus={0}", Param = (int)WarehouseStatus.Dealing });
                            break;
                        default:
                            break;
                    }
                }

                //查询
                var _list = this.BaseEntityRepository.SqlQueryGetPage<View_OrderModify>(db, "select * from View_OrderModify order by Id desc", _sqlWhere, VariableHelper.SaferequestInt(Request.Form["page"]), VariableHelper.SaferequestInt(Request.Form["rows"]));
                //数据解密并脱敏
                foreach (var item in _list.Items)
                {
                    EncryptionFactory.Create(item).HideSensitive();
                }
                _result.Data = new
                {
                    total = _list.TotalItems,
                    rows = from dy in _list.Items
                           select new
                           {
                               ck = dy.Id,
                               s0 = dy.Status,
                               s1 = string.Format("<a href=\"javascript:void(0);\" onclick=\"artDialogExtend.Dialog.Open('" + Url.Action("Detail", "OrderQuery") + "?ID={0}',{{title:'{0}',width:'100%',height:'100%'}});\">{0}</a>{1}", dy.OrderNo, OrderHelper.GetProcessNatureLabel(new OrderHelper.ProcessNature() { IsSystemModify = dy.IsSystemModify })),
                               s2 = dy.SubOrderNo,
                               s3 = dy.MallName,
                               s4 = dy.CustomerName,
                               s5 = dy.Tel,
                               s6 = dy.Mobile,
                               s7 = dy.Zipcode,
                               s8 = AreaService.JoinAreaMessage(new AreaDto() { Province = dy.Province, City = dy.City, District = dy.District }),
                               s9 = dy.Addr,
                               s10 = OrderHelper.GetProcessStatusDisplay(dy.Status, true),
                               s11 = string.Format("{0}<br/>{1}{2}", dy.AddUserName, dy.AddDate.ToString("yyyy-MM-dd HH:mm:ss"), (!string.IsNullOrEmpty(dy.Remark)) ? "<br/>" + dy.Remark : ""),
                               s12 = (!dy.IsSystemModify) ? OrderHelper.GetWarehouseStatusDisplay(dy.ApiIsRead, dy.ApiStatus, true) + ((dy.ApiReplyDate != null) ? "<br/>" + dy.ApiReplyDate.Value.ToString("yyyy-MM-dd HH:mm:ss") : "") + ((dy.ApiReplyMsg != null) ? "<br/>" + dy.ApiReplyMsg : "") : "",
                               s13 = string.Format("{0}", ((dy.AcceptUserDate != null) ? dy.AcceptUserName + "<br/>" + VariableHelper.FormateTime(dy.AcceptUserDate, "yyyy-MM-dd HH:mm:ss") : ""))
                           }
                };
            }
            return _result;
        }
        #endregion

        #region 添加
        [UserPowerAuthorize]
        public ActionResult Add()
        {
            //加载语言包
            ViewBag.LanguagePack = this.GetLanguagePack;

            Int64 _ID = VariableHelper.SaferequestInt64(Request.QueryString["ID"]);
            using (var db = new ebEntities())
            {
                Order objOrder = db.Order.Where(p => p.Id == _ID).SingleOrDefault();
                if (objOrder != null)
                {
                    ViewData["order"] = objOrder;
                    List<OrderDetail> objOrderDetail_List = db.OrderDetail.Where(p => p.OrderId == objOrder.Id && !p.IsSetOrigin && !p.IsDelete && !p.IsExchangeNew).ToList();
                    //最新收货信息集合
                    List<ReceiveDto> objReceiveDto_List = new List<ReceiveDto>();
                    foreach (var _o in objOrderDetail_List)
                    {
                        objReceiveDto_List.Add(OrderReceiveService.GetNewestReceive(_o.OrderNo, _o.SubOrderNo));
                    }
                    ViewData["receive_list"] = objReceiveDto_List;

                    return View(objOrderDetail_List);
                }
                else
                {
                    return RedirectToAction("Index", "Error", new { Type = (int)ErrorType.NoMessage });
                }
            }
        }

        [UserPowerAuthorize(Type = UserPowerAuthorize.ResultType.Json, IsAntiForgeryToken = true)]
        public JsonResult Add_Message()
        {
            //加载语言包
            var _LanguagePack = this.GetLanguagePack;

            JsonResult _result = new JsonResult();
            string _OrderID = VariableHelper.SaferequestStr(Request.Form["OrderID"]);
            string _Remark = VariableHelper.SaferequestStr(Request.Form["Remark"]);
            int _TotalSelect = VariableHelper.SaferequestInt(Request.Form["TotalSelect"]);

            string _SelectIDs = Request.Form["SelectID"];
            string _Sorts = Request.Form["Sort"];
            //如果字段中存在逗号,那么使用同一个Name获取数据时候由于逗号分隔原理,无法取到正确数据
            //string _Addreses = Request.Form["Address"];

            using (var db = new ebEntities())
            {
                using (var Trans = db.Database.BeginTransaction())
                {

OMS.App/Views/OrderModify/Add.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    var _Order = (Samsonite.OMS.Database.Order)ViewData["order"];
    var _DetailList = (List<Samsonite.OMS.Database.OrderDetail>)Model;
    var _ReveiveList = (List<Samsonite.OMS.DTO.ReceiveDto>)ViewData["receive_list"];
    int t = 0;
}
<div class="main">
    <div class="main_edit">
        <form id="subform" method="post">
            <input name="OrderID" type="hidden" value="@_Order.OrderNo" />
           
            <table class="common_table1">
                <tbody>
                    <tr>
                        <th></th>
                        <th>@ViewBag.LanguagePack["ordercancel_edit_sub_order_number"]</th>
                        <th>@ViewBag.LanguagePack["ordercancel_edit_sku"]</th>
                        <th>@ViewBag.LanguagePack["ordermodify_edit_receiver"]</th>
                        <th>@ViewBag.LanguagePack["ordermodify_edit_tel"]</th>
                        <th>@ViewBag.LanguagePack["ordermodify_edit_mobile"]</th>
                        <th>@ViewBag.LanguagePack["ordermodify_edit_zipcode"]</th>
                        <th>@ViewBag.LanguagePack["ordermodify_edit_address"]</th>
                    </tr>
                    @foreach (var _O in _DetailList)
                    {
                        var _Receive = _ReveiveList.Where(p => p.SubOrderNo == _O.SubOrderNo).SingleOrDefault();
                        <tr id="@t">
                            <td>
                                <input id="SelectID_@t" name="SelectID" type="checkbox" value="@_O.Id" />
                                <input id="Sort_@t" name="Sort" type="hidden" class="easyui-textbox" data-options="disabled:true" value="@t" />
                            </td>
                            <td>
                                @_O.SubOrderNo
                            </td>
                            <td>
                                @_O.SKU
                            </td>
                            <td>
                                <input id="Receiver_@t" name="Receiver_@t" type="text" class="easyui-textbox input-medium" data-options="disabled:true" value="@_Receive.Receiver" />
                            </td>
                            <td>
                                <input id="Tel_@t" name="Tel_@t" type="text" class="easyui-textbox input-medium" data-options="disabled:true" value="@_Receive.Tel" />
                            </td>
                            <td>
                                <input id="Cel_@t" name="Mobile_@t" type="text" class="easyui-textbox input-medium" data-options="disabled:true" value="@_Receive.Mobile" />
                            </td>
                            <td>
                                <input id="ZipCode_@t" name="ZipCode_@t" type="text" class="easyui-textbox input-medium" data-options="disabled:true" value="@_Receive.ZipCode" />
                            </td>
                            <td class="textalign_left">
                                <input id="Addr_@t" name="Address_@t" type="text" class="easyui-textbox input-xxlarge" data-options="disabled:true" value="@_Receive.Address" />
                            </td>
                        </tr>
                        t++;
                    }
                    <tr>
                        <td></td>
                        <td class="textalign_left" colspan="7">
                            <input id="CopyButton" type="button" value="@ViewBag.LanguagePack["ordermodify_edit_copy_button"]" class="btn btn-warning" />
                            <label class="label-info">@ViewBag.LanguagePack["ordermodify_edit_copy_button_label"]</label>
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="space_tiny space_spilt"></div>
            <table class="table">
                <tbody>
                    <tr>
                        <th>
                            @ViewBag.LanguagePack["ordermodify_edit_remark"]：
                        </th>
                        <td>
                            <textarea name="Remark" class="easyui-textarea  input-xlarge" style="height:100px;"></textarea>
                        </td>
                    </tr>
                </tbody>
            </table>
        </form>
    </div>
</div>
@section scripts {
    <script type="text/javascript">
        $(function () {
            $('.common_table1').find('input[name=SelectID]').bind('click', function () {
                var _t = $(this).parent().parent().attr("id");
                if ($(this).prop("checked")) {
                    $('#Sort_' + _t).textbox({ disabled: false });
                    $('#Receiver_' + _t).textbox({ disabled: false });
                    $('#Tel_' + _t).textbox({ disabled: false });
                    $('#Cel_' + _t).textbox({ disabled: false });
                    $('#ZipCode_' + _t).textbox({ disabled: false });
                    $('#Addr_' + _t).textbox({ disabled: false });
                }
                else {
                    $('#Sort_' + _t).textbox({ disabled: true });
                    $('#Receiver_' + _t).textbox({ disabled: true });
                    $('#Tel_' + _t).textbox({ disabled: true });
                    $('#Cel_' + _t).textbox({ disabled: true });
                    $('#ZipCode_' + _t).textbox({ disabled: true });
                    $('#Addr_' + _t).textbox({ disabled: true });
                }
            });

            $('#CopyButton').bind('click', function () {
                var _selectIDs = $('.common_table1').find('input[name=SelectID]:checked');
                if (_selectIDs.length > 0) {
                    var _t = _selectIDs.eq(0).parent().parent().attr("id");
                    var _receiver = $('#Receiver_' + _t).textbox('getValue');
                    var _tel = $('#Tel_' + _t).textbox('getValue');
                    var _cel = $('#Cel_' + _t).textbox('getValue');
                    var _zipCode = $('#ZipCode_' + _t).textbox('getValue');
                    var _address = $('#Addr_' + _t).textbox('getValue');

                    //复制数据
                    for (var t = 1; t < _selectIDs.length; t++) {
                        _t = _selectIDs.eq(t).parent().parent().attr("id");
                        $('#Receiver_' + _t).textbox('setValue', _receiver);
                        $('#Tel_' + _t).textbox('setValue', _tel);
                        $('#Cel_' + _t).textbox('setValue', _cel);
                        $('#ZipCode_' + _t).textbox('setValue', _zipCode);
                        $('#Addr_' + _t).textbox('setValue', _address);
                    }
                }
            });
        });
    </script>
}

OMS.App/Views/OrderModify/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    var _QuickTimeList = (List<object[]>)ViewData["quicktime_list"];
    var _processList = (List<object[]>)ViewData["proccess_list"];
    var _WHList = (List<object[]>)ViewData["wh_list"];
}
<div class="main">
    <div class="main_top">@Html.Raw(ViewBag.MenuBar)</div>
    <div class="main_search">
        <form id="SearchForm" action="@Url.Action("ExportExcel", "OrderModify")" method="post">
            <ul>
                <li>
                    @ViewBag.LanguagePack["ordermodify_index_search_order_number"]:
                    <input id="OrderNumber"  name="OrderNumber" type="text" class="easyui-textbox input-xlarge" value="@ViewBag.OrderID" prompt="@ViewBag.LanguagePack["common_search_order"]" />
                </li>
                <li>
                    @ViewBag.LanguagePack["ordermodify_index_search_time"]:
                    <select id="quick_time" name="quick_time" class="easyui-combobox">
                        <option value="0" selected="selected">@ViewBag.LanguagePack["common_select"]</option>
                        @foreach (var _o in _QuickTimeList)
                        {
                            <option value="@_o[0]">@_o[1]</option>
                        }
                    </select>
                    <input id="Time1" name="Time1" type="text" class="input-medium Wdate" onclick="WdatePicker({ dateFmt: 'yyyy-MM-dd' })" />
                    -
                    <input id="Time2" name="Time2"  type="text" class="input-medium Wdate" onclick="WdatePicker({ dateFmt: 'yyyy-MM-dd' })" />
                </li>
                <li>
                    @ViewBag.LanguagePack["ordermodify_index_search_store"]:
                    <input id="StoreName" name="StoreName" style="width:275px;" value="" prompt="@ViewBag.LanguagePack["common_prompt_all_mall"]">
                </li>
                <li>
                    @ViewBag.LanguagePack["ordercancel_index_search_process"]:
                    <select id="ProcessStatus" name="ProcessStatus" class="easyui-combobox">
                        <option value="0" selected="selected">--@ViewBag.LanguagePack["common_all"]--</option>
                        @foreach (var _o in _processList)
                        {
                            <option value="@_o[0]">@_o[1]</option>
                        }
                    </select>
                </li>
                <li>
                    @ViewBag.LanguagePack["ordermodify_index_search_stock_oper"]:
                    <select id="StockStatus" name="StockStatus" class="easyui-combobox">
                        <option value="0" selected="selected">--@ViewBag.LanguagePack["common_all"]--</option>
                        @foreach (var _o in _WHList)
                        {
                            <option value="@_o[0]">@_o[1]</option>
                        }
                    </select>
                </li>
                <li>
                    <input id="SearchButton" type="button" value="@ViewBag.LanguagePack["common_search"]" class="btn btn-info" />
                </li>
            </ul>
        </form>
    </div>
    <div class="main_list">
        <div id="toolbar">
            <a id="edit" href="javascript:void(0)" class="easyui-linkbutton" plain="true"><i class="fa fa-pencil-square-o color_warning"></i>@ViewBag.LanguagePack["common_edit"]</a>
            <a id="delete" href="javascript:void(0)" class="easyui-linkbutton" plain="true"><i class="fa fa-close color_danger"></i>@ViewBag.LanguagePack["common_delete"]</a>
            <a id="detail" href="javascript:void(0)" class="easyui-linkbutton" plain="true"><i class="fa fa-window-restore color_success"></i>@ViewBag.LanguagePack["common_detail"]</a>
            <a id="manual" href="javascript:void(0)" class="easyui-linkbutton" plain="true"><i class="fa fa-user color_primary"></i>@ViewBag.LanguagePack["common_manual"]</a>
            <span class="toolbar-separator"></span>
            <a id="exportexcel" href="javascript:void(0)" class="easyui-linkbutton" plain="true"><i class="fa fa-upload color_primary"></i>@ViewBag.LanguagePack["common_export"]</a>
            <span class="toolbar-separator"></span>
            <a id="refresh" href="javascript:void(0)" class="easyui-linkbutton" plain="true" power="false"><i class="fa fa-refresh color_info"></i>@ViewBag.LanguagePack["common_refresh"]</a>
        </div>
        <table id="dg">
            <thead>
                <tr>
                    <th data-options="field:'ck',checkbox:true">
                    </th>
                    <th data-options="field:'s1',align:'left'">
                        @ViewBag.LanguagePack["ordermodify_index_order_number"]
                    </th>
                    <th data-options="field:'s2',align:'left'">
                        @ViewBag.LanguagePack["ordermodify_index_sub_order_number"]
                    </th>
                    <th data-options="field:'s3',align:'center'">
                        @ViewBag.LanguagePack["ordermodify_index_store"]
                    </th>
                    <th data-options="field:'s4',align:'center'">
                        @ViewBag.LanguagePack["ordermodify_index_customer"]
                    </th>
                    <th data-options="field:'s5',align:'center'">
                        @ViewBag.LanguagePack["ordermodify_index_tel"]
                    </th>
                    <th data-options="field:'s6',align:'center'">
                        @ViewBag.LanguagePack["ordermodify_index_mobile"]
                    </th>
                    <th data-options="field:'s7',align:'left'">
                        @ViewBag.LanguagePack["ordermodify_index_zipcode"]
                    </th>
                    @*<th data-options="field:'s8',align:'left'">
                            @ViewBag.LanguagePack["ordermodify_index_area"]
                        </th>*@
                    <th data-options="field:'s9',align:'left'">
                        @ViewBag.LanguagePack["ordermodify_index_address"]
                    </th>
                    <th data-options="field:'s10',align:'center'">
                        @ViewBag.LanguagePack["ordermodify_index_process"]
                    </th>
                    <th data-options="field:'s11',align:'left'">
                        @ViewBag.LanguagePack["ordermodify_index_oper_message"]
                    </th>
                    <th data-options="field:'s12',align:'left'">
                        @ViewBag.LanguagePack["ordermodify_index_stock_reply"]
                    </th>
                    <th data-options="field:'s13',align:'left'">
                        @ViewBag.LanguagePack["ordermodify_index_confirm_message"]
                    </th>
                </tr>
            </thead>
        </table>
    </div>
</div>
@section scripts {
    @Scripts.Render("~/Content/js-library/my97datepicker/4.7.2/WdatePicker.js")
    <script type="text/javascript">
        $(function () {
            //初始化店铺列表
            $('#StoreName').combotree({
                url: '@Url.Action("Mall_Message", "Common")',
                queryParams: {
                    mall_type: 'all',
                    show_type: 'comboTree'
                },
                multiple: true
            });
            //工具栏
            easyUIExtend.Grid.Toolbar($('#toolbar'), {
                powerTools: ('@ViewBag.FunctionPower').split(','),
                hideTools: getHideToolBar()
            });
            //列表
            easyUIExtend.Grid.List($('#dg'), {
                toolbar: '#toolbar',
                url: '@Url.Action("Index_Message", "OrderModify")',
                onClickRow:function(index,row){
                    //确定操作按钮可用性
                    easyUIExtend.Grid.Toolbar($('#toolbar'), {
                        powerTools: ('@ViewBag.FunctionPower').split(','),
                        hideTools: getHideToolBar(parseInt(row.s0))
                    });
                }
            });
            //搜索
            $('#SearchButton').bind('click', function () {
                easyUIExtend.Grid.Search($('#dg'), {
                    orderid: $('#OrderNumber').val(),
                    time1: $('#Time1').val(),
                    time2: $('#Time2').val(),
                    store: $("#StoreName").combotree("getValues").join(','),
                    proccess_status: $('#ProcessStatus').combobox('getValue'),
                    stock_status: $('#StockStatus').combobox('getValue')
                });
                //确定操作按钮可用性
                easyUIExtend.Grid.Toolbar($('#toolbar'), {
                    powerTools: ('@ViewBag.FunctionPower').split(','),
                    hideTools: getHideToolBar()
                });
            });
            $('#toolbar').find('#edit').bind('click', function () {
                easyUIExtend.Grid.SaveOper($('#dg'), {
                    url: '@Url.Action("Edit", "OrderModify")?id=$',
                    title: '@ViewBag.LanguagePack["common_edit"]',
                    width: '100%',
                    height: '100%',
                    dataUrl: '@Url.Action("Edit_Message", "OrderModify")'
                });
            });
            $('#toolbar').find('#delete').bind('click', function () {
                easyUIExtend.Grid.ComplexOper($('#dg'), '@Url.Action("Delete_Message", "OrderModify")');
            });
            $('#toolbar').find('#detail').bind('click', function () {
                easyUIExtend.Grid.SingleOper($('#dg'), {
                    url: '@Url.Action("Detail", "OrderModify")?id=$',
                    title: '@ViewBag.LanguagePack["common_detail"]',
                    width: '100%',
                    height: '100%'
                });
            });
            $('#toolbar').find('#manual').bind('click', function () {
                easyUIExtend.Grid.ComplexSaveOper($('#dg'), {
                    url: '@Url.Action("Manual", "OrderModify")?id=$',
                    title: '@ViewBag.LanguagePack["common_manual"]',
                    width: 750,
                    height: 450,
                    dataUrl: '@Url.Action("Manual_Message", "OrderModify")'
                });
            });
            //导出数据
            $('#toolbar').find('#exportexcel').bind('click', function () {
                $('#SearchForm').submit();
            });
            $('#toolbar').find('#refresh').bind('click', function () {
                easyUIExtend.Grid.Refresh($('#dg'));
            });
            $('#quick_time').combobox({
                onChange: function (value) {
                    if (value > 0) {
                        commonJs.sysAjaxFunction({
                            url: '@Url.Action("QuickTime_Message", "Common")',
                            para: { id: value, format: 'yyyy-MM-dd' },
                            isload: false,
                            func: function (data) {
                                data = eval('(' + data + ')');
                                $('#Time1').val(data.t1);
                                $('#Time2').val(data.t2);
                            }
                        });
                    }
                    else {
                        $('#Time1').val('');
                        $('#Time2').val('');
                    }
                }
            });
        });

        //获取工具栏
        //edit/delete/manual/detail
        function getHideToolBar(processState)
        {
            var _result;
            if(processState === undefined){
                processState=parseInt($('#ProcessStatus').combobox('getValue'));
            }
            switch (processState)
            {
                case @Convert.ToInt32(Samsonite.OMS.DTO.ProcessStatus.Modify):
                    _result=new Array('manual');
                    break;
                case @Convert.ToInt32(Samsonite.OMS.DTO.ProcessStatus.ModifyWHSure):
                    _result=new Array('edit','delete','manual');
                    break;
                case @Convert.ToInt32(Samsonite.OMS.DTO.ProcessStatus.ModifyComplete):
                    _result=new Array('edit','delete','manual');
                    break;
                case @Convert.ToInt32(Samsonite.OMS.DTO.ProcessStatus.ModifyFail):
                    _result=new Array('edit','delete');
                    break;
                case @Convert.ToInt32(Samsonite.OMS.DTO.ProcessStatus.Delete):
                    _result=new Array('edit','delete','manual');
                    break;
                default:
                    _result=new Array();
                    break;
            }
            return _result;
        }
    </script>
}

OMS.App/Views/OrderModify/Manual.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="main">
    <div class="main_edit">
        <form id="subform" method="post">
            <input name="ID" type="hidden" value="@ViewBag.IDs" />
            <table class="table">
                <tbody>
                    <tr>
                        <th>
                            @ViewBag.LanguagePack["ordermodify_manual_result"]：
                        </th>
                        <td>
                            <input id="r1" name="Result" value="1" type="radio" checked="checked" /><label for="r1">@ViewBag.LanguagePack["common_confirmed"]</label>
                            <input id="r2" name="Result" value="0" type="radio" /><label for="r2">@ViewBag.LanguagePack["common_delete"]</label>
                        </td>
                    </tr>
                    <tr>
                        <th>
                            @ViewBag.LanguagePack["ordermodify_manual_remark"]：
                        </th>
                        <td>
                            <textarea name="Remark" class="easyui-textarea  input-xlarge" style="height:100px;"></textarea>
                        </td>
                    </tr>
                </tbody>
            </table>
        </form>
    </div>
</div>