OMS.App/Controllers/Function/FunctionGroupController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

using Samsonite.OMS.DTO;
using Samsonite.OMS.Database;
using Samsonite.OMS.Service;
using Samsonite.Utility.Common;

namespace OMS.App.Controllers
{
    public class FunctionGroupController : BaseController
    {
        //
        // GET: /FunctionGroup/

        #region 查询
        [UserPowerAuthorize]
        public ActionResult Index()
        {
            //加载语言包
            ViewBag.LanguagePack = this.GetLanguagePack;
            //菜单栏
            ViewBag.MenuBar = this.MenuBar();
            //功能权限
            ViewBag.FunctionPower = this.FunctionPowers();

            return View();
        }

        [UserPowerAuthorize(Type = UserPowerAuthorize.ResultType.Json)]
        public JsonResult Index_Message()
        {
            JsonResult _result = new JsonResult();
            string _keyword = VariableHelper.SaferequestStr(Request.Form["keyword"]);
            using (var db = new ebEntities())
            {
                var _lambda = db.SysFunctionGroup.AsQueryable();

                //搜索条件
                if (!string.IsNullOrEmpty(_keyword))
                {
                    _lambda = _lambda.Where(p => p.GroupName.Contains(_keyword));
                }
                //查询
                var _list = this.BaseEntityRepository.GetPage(VariableHelper.SaferequestInt(Request.Form["page"]), VariableHelper.SaferequestInt(Request.Form["rows"]), _lambda.AsNoTracking(), p => p.Rootid, true);
                _result.Data = new
                {
                    total = _list.TotalItems,
                    rows = from dy in _list.Items
                           select new
                           {
                               ck = dy.Groupid,
                               s1 = dy.GroupName,
                               s2 = ((!string.IsNullOrEmpty(dy.GroupIcon)) ? string.Format("<i class=\"common-icon fa {0}\"></i>", dy.GroupIcon) : string.Empty),
                               s3 = dy.Rootid
                           }
                };
                return _result;
            }
        }
        #endregion

        #region 添加
        [UserPowerAuthorize]
        public ActionResult Add()
        {
            //加载语言包
            ViewBag.LanguagePack = this.GetLanguagePack;

            return View();
        }

        [UserPowerAuthorize(Type = UserPowerAuthorize.ResultType.Json, IsAntiForgeryToken = true)]
        public JsonResult Add_Message()
        {
            JsonResult _result = new JsonResult();
            string _GroupName = VariableHelper.SaferequestStr(Request.Form["GroupName"]);
            string _GroupIcon = VariableHelper.SaferequestStr(Request.Form["GroupIcon"]);
            string _GroupMemo = VariableHelper.SaferequestEditor(Request.Form["GroupMemo"]);
            using (var db = new ebEntities())
            {
                try
                {
                    if (string.IsNullOrEmpty(_GroupName))
                    {
                        throw new Exception("栏目名称不能为空");
                    }

                    SysFunctionGroup objSysFunctionGroup = db.SysFunctionGroup.Where(p => p.GroupName == _GroupName).SingleOrDefault();
                    if (objSysFunctionGroup != null)
                    {
                        throw new Exception("栏目已经存在，请勿重复");
                    }

                    int _RootID = db.Database.SqlQuery<int>("select isnull(Max(Rootid),0) as MaxID from SysFunctionGroup").SingleOrDefault() + 1;

                    SysFunctionGroup objData = new SysFunctionGroup()
                    {
                        GroupName = _GroupName,
                        GroupIcon = _GroupIcon,
                        Rootid = _RootID,
                        Parentid = 0,
                        SeqNumber = 0,
                        GroupMemo = _GroupMemo,
                        CreateTime = DateTime.Now
                    };
                    db.SysFunctionGroup.Add(objData);
                    db.SaveChanges();
                    //添加日志
                    AppLogService.InsertLog<SysFunctionGroup>(objData, objData.Groupid.ToString());
                    //返回信息
                    _result.Data = new
                    {
                        result = true,
                        msg = "数据保存成功"
                    };
                }
                catch (Exception ex)
                {
                    _result.Data = new
                    {
                        result = false,
                        msg = ex.Message
                    };
                }
                return _result;
            }
        }
        #endregion

        #region 编辑
        [UserPowerAuthorize]
        public ActionResult Edit()
        {
            //加载语言包
            ViewBag.LanguagePack = this.GetLanguagePack;

            int _GroupID = VariableHelper.SaferequestInt(Request.QueryString["ID"]);
            using (var db = new ebEntities())
            {
                SysFunctionGroup objSysFunctionGroup = db.SysFunctionGroup.Where(p => p.Groupid == _GroupID).SingleOrDefault();
                if (objSysFunctionGroup != null)
                {
                    return View(objSysFunctionGroup);
                }
                else
                {
                    return RedirectToAction("Index", "Error", new { Type = (int)ErrorType.NoMessage });
                }
            }
        }

        [UserPowerAuthorize(Type = UserPowerAuthorize.ResultType.Json, IsAntiForgeryToken = true)]
        public JsonResult Edit_Message()
        {
            JsonResult _result = new JsonResult();
            int _GroupID = VariableHelper.SaferequestInt(Request.Form["ID"]);
            string _GroupName = VariableHelper.SaferequestStr(Request.Form["GroupName"]);
            string _GroupIcon = VariableHelper.SaferequestStr(Request.Form["GroupIcon"]);
            string _GroupMemo = VariableHelper.SaferequestEditor(Request.Form["GroupMemo"]);
            using (var db = new ebEntities())
            {
                try
                {
                    if (string.IsNullOrEmpty(_GroupName))
                    {
                        throw new Exception("栏目名称不能为空");
                    }

                    SysFunctionGroup objSysFunctionGroup = db.SysFunctionGroup.Where(p => p.GroupName == _GroupName && p.Groupid != _GroupID).SingleOrDefault();
                    if (objSysFunctionGroup != null)
                    {
                        throw new Exception("栏目已经存在，请勿重复");
                    }

                    SysFunctionGroup objData = db.SysFunctionGroup.Where(p => p.Groupid == _GroupID).SingleOrDefault();
                    if (objData != null)
                    {
                        objData.GroupName = _GroupName;
                        objData.GroupIcon = _GroupIcon;
                        objData.GroupMemo = _GroupMemo;
                        db.SaveChanges();
                        //添加日志
                        AppLogService.UpdateLog<SysFunctionGroup>(objData, objData.Groupid.ToString());
                        //返回信息
                        _result.Data = new
                        {
                            result = true,
                            msg = "数据保存成功"
                        };
                    }
                    else
                    {
                        throw new Exception("数据读取失败");
                    }
                }
                catch (Exception ex)
                {
                    _result.Data = new
                    {
                        result = false,
                        msg = ex.Message
                    };
                }
                return _result;
            }
        }
        #endregion

        #region 删除
        [UserPowerAuthorize(Type = UserPowerAuthorize.ResultType.Json, IsAntiForgeryToken = true)]
        public JsonResult Delete_Message()
        {
            JsonResult _result = new JsonResult();
            string _IDs = VariableHelper.SaferequestStr(Request.Form["ID"]);
            using (var db = new ebEntities())
            {
                using (var Trans = db.Database.BeginTransaction())
                {
                    try
                    {
                        if (string.IsNullOrEmpty(_IDs))
                        {
                            throw new Exception("请至少选择一条要操作的数据");
                        }

                        SysFunctionGroup objSysFunctionGroup = new SysFunctionGroup();
                        foreach (string _str in _IDs.Split(','))
                        {
                            int _ID = VariableHelper.SaferequestInt(_str);
                            objSysFunctionGroup = db.SysFunctionGroup.Where(p => p.Groupid == _ID).SingleOrDefault();
                            if (objSysFunctionGroup != null)
                            {
                                db.Database.ExecuteSqlCommand("delete from SysFunction where GroupID={0}", _ID);
                                db.SysFunctionGroup.Remove(objSysFunctionGroup);
                            }
                            else
                            {
                                throw new Exception(string.Format("{0}:{1}", _str, "信息不存在或已被删除"));
                            }
                        }
                        db.SaveChanges();
                        Trans.Commit();
                        //添加日志
                        AppLogService.DeleteLog("SysFunctionGroup,SysFunction", _IDs);
                        //返回信息
                        _result.Data = new
                        {
                            result = true,
                            msg = "数据删除成功"
                        };
                    }
                    catch (Exception ex)
                    {
                        Trans.Rollback();

OMS.App/Views/FunctionGroup/Add.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="main">
    <div class="main_edit">
        <form id="subform" method="post">
            <table class="table">
                <tbody>
                    <tr>
                        <th>
                            <span class="color_danger">*</span>栏目名称：
                        </th>
                        <td>
                            <input name="GroupName" type="text" class="easyui-textbox input-xlarge" />
                        </td>
                    </tr>
                    <tr>
                        <th>
                            栏目图标：
                        </th>
                        <td>
                            <span id="show_icon"></span>
                            <input name="GroupIcon" type="hidden" value="" />
                            <input id="sicon" type="button" value="选择图标" class="btn btn-warning" onclick="selectIcon()" />
                        </td>
                    </tr>
                    <tr>
                        <th>
                            简要描述：
                        </th>
                        <td>
                            <textarea name="GroupMemo" class="easyui-textarea  input-xlarge" style="height:100px;"></textarea>
                        </td>
                    </tr>
                </tbody>
            </table>
        </form>
    </div>
</div>
@section scripts {
    <script type="text/javascript">
        function DoIconMessage(css) {
            $('#show_icon').html("<i class=\"fa " + css + "\"></i><label class=\"label-info\">" + css + "</label>");
            $('input[name=GroupIcon]').val(css);
            artDialogExtend.Dialog.Close();
        }

        function selectIcon() {
            artDialogExtend.Dialog.Open('@Url.Action("SelectIcon","Common")',
            {
                title: '选择图标',
                width: '100%',
                height: '100%'
            });
        }
    </script>
}

OMS.App/Views/FunctionGroup/Edit.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    var _m = Model;
}
<div class="main">
    <div class="main_edit">
        <form id="subform" method="post">
            <input name="ID" type="hidden" value="@_m.Groupid" />
            <table class="table">
                <tbody>
                    <tr>
                        <th>
                            <span class="color_danger">*</span>栏目名称：
                        </th>
                        <td>
                            <input name="GroupName" type="text" class="easyui-textbox input-xlarge" value="@_m.GroupName"/>
                        </td>
                    </tr>
                    <tr>
                        <th>
                            栏目图标：
                        </th>
                        <td>
                            <span id="show_icon"><i class="fa @_m.GroupIcon"></i><label class="label-info">@_m.GroupIcon</label></span>
                            <input name="GroupIcon" type="hidden" value="@_m.GroupIcon" />
                            <input id="sicon" type="button" value="选择图标" class="btn btn-warning" onclick="selectIcon()" />
                        </td>
                    </tr>
                    <tr>
                        <th>
                            简要描述：
                        </th>
                        <td>
                            <textarea name="GroupMemo" class="easyui-textarea  input-xlarge" style="height:100px;">@_m.GroupMemo</textarea>
                        </td>
                    </tr>
                </tbody>
            </table>
        </form>
    </div>
</div>
@section scripts {
    <script type="text/javascript">
        function DoIconMessage(css) {
            $('#show_icon').html("<i class=\"fa " + css + "\"></i><label class=\"label-info\">" + css + "</label>");
            $('input[name=GroupIcon]').val(css);
            artDialogExtend.Dialog.Close();
        }

        function selectIcon() {
            artDialogExtend.Dialog.Open('@Url.Action("SelectIcon","Common")',
            {
                title: '选择图标',
                width: '100%',
                height: '100%'
            });
        }
    </script>
}

OMS.App/Views/FunctionGroup/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="main">
    <div class="main_top">@Html.Raw(ViewBag.MenuBar)</div>
    <div class="main_search">
        <ul>
            <li>
                <input id="SearchKey" type="text" class="easyui-textbox input-large" prompt="搜索关键字" />
            </li>
            <li>
                <input id="SearchButton" type="button" value="查询" class="btn btn-info" />
            </li>
        </ul>
    </div>
    <div class="main_list">
        <div id="toolbar">
            <a id="add" href="javascript:void(0)" class="easyui-linkbutton" plain="true"><i class="fa fa-plus color_success"></i>添加</a>
            <a id="edit" href="javascript:void(0)" class="easyui-linkbutton" plain="true"><i class="fa fa-pencil-square-o color_warning"></i>编辑</a>
            <a id="delete" href="javascript:void(0)" class="easyui-linkbutton" plain="true"><i class="fa fa-close color_danger"></i>删除</a>
            <span class="toolbar-separator"></span>
            <a id="refresh" href="javascript:void(0)" class="easyui-linkbutton" plain="true" power="false"><i class="fa fa-refresh color_info"></i>刷新</a>
        </div>
        <table id="dg">
            <thead>
                <tr>
                    <th data-options="field:'ck',checkbox:true">
                    </th>
                    <th data-options="field:'s1',width:50,align:'left'">
                        分组名称
                    </th>
                    <th data-options="field:'s2',align:'center'">
                        分组图标
                    </th>
                    <th data-options="field:'s3',align:'center'">
                        排序
                    </th>
                </tr>
            </thead>
        </table>
    </div>
</div>
@section scripts {
    <script type="text/javascript">
        $(function () {
            //工具栏
            easyUIExtend.Grid.Toolbar($('#toolbar'), {
                powerTools: ('@ViewBag.FunctionPower').split(',')
            });
            //列表
            easyUIExtend.Grid.List($('#dg'), {
                toolbar: '#toolbar',
                url: '@Url.Action("Index_Message","FunctionGroup")'
            });
            //搜索
            $('#SearchButton').bind('click', function () {
                easyUIExtend.Grid.Search($('#dg'), {
                    keyword: $('#SearchKey').val()
                });
            });
            //操作
            $('#toolbar').find('#add').bind('click', function () {
                easyUIExtend.Grid.SaveDialog({
                    url: '@Url.Action("Add", "FunctionGroup")',
                    title: '添加信息',
                    width: '100%',
                    height: '100%',
                    dataUrl: '@Url.Action("Add_Message", "FunctionGroup")'
                });
            });
            $('#toolbar').find('#edit').bind('click', function () {
                easyUIExtend.Grid.SaveOper($('#dg'), {
                    url: '@Url.Action("Edit", "FunctionGroup")?id=$',
                    title: '编辑信息',
                    width: '100%',
                    height: '100%',
                    dataUrl: '@Url.Action("Edit_Message", "FunctionGroup")'
                });
            });
            $('#toolbar').find('#delete').bind('click', function () {
                easyUIExtend.Grid.ComplexOper($('#dg'), '@Url.Action("Delete_Message", "FunctionGroup")');
            });
            $('#toolbar').find('#refresh').bind('click', function () {
                easyUIExtend.Grid.Refresh($('#dg'));
            });
        });
    </script>
}