OMS.App/Controllers/Log/ApiLogController.cs
using System.Data.Entity;
using System.Data.Entity.SqlServer;
using System.Linq;
using System.Web.Mvc;

using Samsonite.OMS.Database;
using Samsonite.Utility.Common;

using OMS.App.Helper;


namespace OMS.App.Controllers
{
    public class ApiLogController : BaseController
    {
        //
        // GET: /ApiLog/

        #region 服务日志
        [UserPowerAuthorize]
        public ActionResult Index()
        {
            //加载语言包
            ViewBag.LanguagePack = this.GetLanguagePack;
            //菜单栏
            ViewBag.MenuBar = this.MenuBar();
            //功能权限
            ViewBag.FunctionPower = this.FunctionPowers();
            //API用途
            ViewData["type_list"] = APIHelper.APITypeObject();

            return View();
        }

        [UserPowerAuthorize(Type = UserPowerAuthorize.ResultType.Json)]
        public JsonResult Index_Message()
        {
            JsonResult _result = new JsonResult();
            int _type = VariableHelper.SaferequestInt(Request.Form["type"]);
            string _keyword = VariableHelper.SaferequestStr(Request.Form["keyword"]);
            int _state = VariableHelper.SaferequestInt(Request.Form["state"]);
            string _time = VariableHelper.SaferequestStr(Request.Form["time"]);

            using (var db = new logEntities())
            {
                var _lambda = db.WebApiAccessLog.AsQueryable();

                if (_type > 0)
                {
                    _lambda = _lambda.Where(p => p.LogType == _type);
                }

                if (!string.IsNullOrEmpty(_keyword))
                {
                    _lambda = _lambda.Where(p => p.Ip.Contains(_keyword) || p.Url.Contains(_keyword));
                }

                if (_state > 0)
                {
                    if (_state == 1)
                    {
                        _lambda = _lambda.Where(p => !p.State);
                    }
                    else if (_state == 2)
                    {
                        _lambda = _lambda.Where(p => p.State);
                    }
                }

                if (!string.IsNullOrEmpty(_time))
                {
                    var _datetime = VariableHelper.SaferequestTime(_time);
                    _lambda = _lambda.Where(p => SqlFunctions.DateDiff("day", p.CreateTime, _datetime) == 0);
                }

                //查询
                var _list = this.BaseEntityRepository.GetPage(VariableHelper.SaferequestInt(Request.Form["page"]), VariableHelper.SaferequestInt(Request.Form["rows"]), _lambda.AsNoTracking(), p => p.id, false);
                _result.Data = new
                {
                    total = _list.TotalItems,
                    rows = from dy in _list.Items
                           select new
                           {
                               ck = dy.id,
                               s1 = dy.Ip,
                               s2 = dy.Url,
                               s3 = dy.RequestID,
                               s4 = (dy.State) ? "<label class=\"color_primary\">成功</label>" : "<label class=\"color_danger\">失败<label>",
                               s5 = dy.Remark,
                               s6 = dy.CreateTime.ToString("yyyy-MM-dd HH:mm:ss")
                           }
                };
                return _result;
            }
        }
        #endregion
    }
}

OMS.App/Views/ApiLog/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    List<object[]> _LogTypeList = (List<object[]>)ViewData["type_list"];
}
<div class="main">
    <div class="main_top">@Html.Raw(ViewBag.MenuBar)</div>
    <div class="main_search">
        <ul>
            <li>
                <select id="Type" class="easyui-combobox">
                    <option value="0">--全部用途--</option>
                    @{
                        foreach (var _o in _LogTypeList)
                        {
                            <option value="@_o[0]">@_o[1]</option>
                        }
                    }
                </select>
            </li>
            <li>
                <input id="SearchKey" type="text" class="easyui-textbox input-xxlarge" prompt="搜索IP或关键字" />
            </li>
            <li>
                日期:
                <input id="SearchTime" type="text" class="input-medium Wdate" onclick="WdatePicker({dateFmt:'yyyy-MM-dd'})" />
            </li>
            <li>
                <select id="State" class="easyui-combobox">
                    <option value="0">--全部--</option>
                    <option value="2">成功</option>
                    <option value="1">失败</option>
                </select>
            </li>
            <li>
                <input id="SearchButton" type="button" value="查询" class="btn btn-info" />
            </li>
        </ul>
    </div>
    <div class="main_list">
        <div id="toolbar">
            <a id="refresh" href="javascript:void(0)" class="easyui-linkbutton" plain="true" power="false"><i class="fa fa-refresh color_info"></i>刷新</a>
        </div>
        <table id="dg">
            <thead>
                <tr>
                    <th data-options="field:'s1',align:'center'">
                        访问IP
                    </th>
                    <th data-options="field:'s2',align:'left'">
                        访问信息
                    </th>
                    <th data-options="field:'s3',align:'left'">
                        访问请求流水号
                    </th>
                    <th data-options="field:'s4',align:'center'">
                        访问结果
                    </th>
                    <th data-options="field:'s5',align:'left'">
                        备注信息
                    </th>
                    <th data-options="field:'s6',align:'left'">
                        访问时间
                    </th>
                </tr>
            </thead>
        </table>
    </div>
</div>
@section scripts {
    @Scripts.Render("~/Content/js-library/my97datepicker/4.7.2/WdatePicker.js")
    <script type="text/javascript">
        $(function () {
            //工具栏
            easyUIExtend.Grid.Toolbar($('#toolbar'), {
                powerTools: ('@ViewBag.FunctionPower').split(',')
            });
            //列表
            easyUIExtend.Grid.List($('#dg'), {
                toolbar: '#toolbar',
                url: '@Url.Action("Index_Message","ApiLog")',
                pageSize: 15
            });
            //搜索
            $('#SearchButton').bind('click', function () {
                easyUIExtend.Grid.Search($('#dg'), {
                    type: $('#Type').combobox("getValue"),
                    keyword: $('#SearchKey').val(),
                    time: $('#SearchTime').val(),
                    state: $('#State').combobox("getValue")
                });
            });
            $('#toolbar').find('#refresh').bind('click', function () {
                easyUIExtend.Grid.Refresh($('#dg'));
            });
        });
    </script>
}