OMS.App/Controllers/Config/ServiceConfigController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.SqlServer;
using System.Linq;
using System.Web.Mvc;

using Samsonite.OMS.DTO;
using Samsonite.OMS.Database;
using Samsonite.OMS.Service;
using Samsonite.Utility.Common;

using OMS.App.Helper;

namespace OMS.App.Controllers
{
    public class ServiceConfigController : BaseController
    {
        //
        // GET: /ServiceConfig/

        #region 查询
        [UserPowerAuthorize]
        public ActionResult Index()
        {
            //加载语言包
            ViewBag.LanguagePack = this.GetLanguagePack;
            //菜单栏
            ViewBag.MenuBar = this.MenuBar();
            //功能权限
            ViewBag.FunctionPower = this.FunctionPowers();
            //服务列表
            using (var db = new ebEntities())
            {
                ViewData["service_list"] = db.ServiceModuleInfo.ToList();
            }
            //执行状态
            ViewData["service_status_list"] = ServiceHelper.ServiceStatusObject();
            //操作类型
            ViewData["job_type_list"] = ServiceHelper.JobTypeObject();
            //操作状态
            ViewData["job_status_list"] = ServiceHelper.JobStatusObject();

            return View();
        }

        [UserPowerAuthorize(Type = UserPowerAuthorize.ResultType.Json)]
        public JsonResult Index_Message()
        {
            JsonResult _result = new JsonResult();
            string _keyword = VariableHelper.SaferequestStr(Request.Form["keyword"]);
            int _status = VariableHelper.SaferequestInt(Request.Form["status"]);
            int _isrun = VariableHelper.SaferequestInt(Request.Form["isrun"]);
            using (var db = new ebEntities())
            {
                var _lambda = db.ServiceModuleInfo.AsQueryable();

                //搜索条件
                if (!string.IsNullOrEmpty(_keyword))
                {
                    _lambda = _lambda.Where(p => p.ModuleTitle.Contains(_keyword));
                }

                if (_status > 0)
                {
                    _lambda = _lambda.Where(p => p.Status == (_status - 1));
                }

                if (_isrun > 0)
                {
                    _lambda = _lambda.Where(p => p.IsRun);
                }

                //查询
                var _list = this.BaseEntityRepository.GetPage(VariableHelper.SaferequestInt(Request.Form["page"]), VariableHelper.SaferequestInt(Request.Form["rows"]), _lambda.AsNoTracking(), p => p.SortID, true);
                _result.Data = new
                {
                    total = _list.TotalItems,
                    rows = from dy in _list.Items
                           select new
                           {
                               ck = dy.ModuleID,
                               s1 = dy.ModuleTitle,
                               s2 = dy.ModuleMark,
                               s3 = dy.ModuleType,
                               s4 = GetModuleRunType(dy.FixType, dy.FixTime),
                               s5 = dy.SortID,
                               s6 = ServiceHelper.GetServiceStatusDisplay(dy.Status, true),
                               s7 = GetOperButton(dy.ModuleID, dy.IsRun, dy.Status),
                               s8 = (dy.NextRunTime == null) ? "--" : dy.NextRunTime.Value.ToString("yyyy-MM-dd HH:mm:ss"),
                               s9 = (dy.IsRun) ? "<label class=\"fa fa-check color_primary\"></label>" : "<label class=\"fa fa-close color_danger\"></label>",
                               s10 = (dy.IsNotify) ? "<label class=\"fa fa-check color_primary\"></label>" : "<label class=\"fa fa-close color_danger\"></label>",
                               s11 = dy.Remark
                           }
                };
                return _result;
            }
        }

        private string GetModuleRunType(int objFixType, string objFixTime)
        {
            string _result = string.Empty;
            if (objFixType == 1)
            {
                _result = $"每隔{(VariableHelper.SaferequestDouble(objFixTime) / 60)}分钟执行一次服务";
            }
            else
            {
                _result = $"每天{objFixTime}定时执行一次服务";
            }
            return _result;
        }

        private string GetOperButton(int objModuleID, bool objIsRun, int objStatus)
        {
            string _result = string.Empty;
            if (objIsRun)
            {
                switch (objStatus)
                {
                    case (int)ServiceStatus.Stop:
                        _result = $"<a href=\"javascript:startService({objModuleID})\" class=\"fa fa-play-circle color_primary\">&nbsp;</a>";
                        break;
                    case (int)ServiceStatus.Runing:
                        _result = $"<a href=\"javascript:pauseService({objModuleID})\" class=\"fa fa-pause color_warning\">&nbsp;</a>";
                        break;
                    case (int)ServiceStatus.Pause:
                        _result = $"<a href=\"javascript:continueService({objModuleID})\" class=\"fa fa-play color_success\">&nbsp;</a>";
                        break;
                    default:
                        break;
                }
            }
            return _result;
        }
        #endregion

        #region 添加
        [UserPowerAuthorize]
        public ActionResult Add()
        {
            //加载语言包
            ViewBag.LanguagePack = this.GetLanguagePack;

            return View();
        }

        [UserPowerAuthorize(Type = UserPowerAuthorize.ResultType.Json, IsAntiForgeryToken = true)]
        public JsonResult Add_Message()
        {
            JsonResult _result = new JsonResult();
            string _ModuleTitle = VariableHelper.SaferequestStr(Request.Form["ModuleTitle"]);
            string _ModuleWorkflowID = VariableHelper.SaferequestStr(Request.Form["ModuleWorkflowID"]);
            string _ModuleMark = VariableHelper.SaferequestStr(Request.Form["ModuleMark"]);
            string _ModuleAssembly = VariableHelper.SaferequestStr(Request.Form["ModuleAssembly"]);
            string _ModuleType = VariableHelper.SaferequestStr(Request.Form["ModuleType"]);
            string _ModuleBLL = VariableHelper.SaferequestStr(Request.Form["ModuleBLL"]);
            int _FixType = VariableHelper.SaferequestInt(Request.Form["FixType"]);
            string _FixTime = VariableHelper.SaferequestStr(Request.Form["FixTime"]);
            string _Remark = VariableHelper.SaferequestEditor(Request.Form["Remark"]);
            int _IsRun = VariableHelper.SaferequestInt(Request.Form["IsRun"]);
            int _IsNotify = VariableHelper.SaferequestInt(Request.Form["IsNotify"]);
            int _SortID = 0;

            using (var db = new ebEntities())
            {
                try
                {
                    if (string.IsNullOrEmpty(_ModuleTitle))
                    {
                        throw new Exception("服务名称不能为空");
                    }

                    if (string.IsNullOrEmpty(_ModuleMark))
                    {
                        throw new Exception("服务标识不能为空");
                    }
                    else
                    {
                        ServiceModuleInfo objServiceModuleInfo = db.ServiceModuleInfo.Where(p => p.ModuleMark == _ModuleMark).SingleOrDefault();
                        if (objServiceModuleInfo != null)
                        {
                            throw new Exception("服务标识已经存在，请勿重复");
                        }
                    }

                    if (string.IsNullOrEmpty(_ModuleAssembly))
                    {
                        throw new Exception("Assembly不能为空");
                    }

                    if (string.IsNullOrEmpty(_ModuleType))
                    {
                        throw new Exception("Class不能为空");
                    }

                    if (string.IsNullOrEmpty(_ModuleBLL))
                    {
                        throw new Exception("BLL不能为空");
                    }

                    _SortID = db.Database.SqlQuery<int>("select isnull(Max(SortID),0) As SortID from ServiceModuleInfo").SingleOrDefault() + 1;

                    ServiceModuleInfo objData = new ServiceModuleInfo()
                    {
                        ModuleTitle = _ModuleTitle,
                        ModuleWorkflowID = _ModuleWorkflowID,
                        ModuleMark = _ModuleMark,
                        ModuleAssembly = _ModuleAssembly,
                        ModuleType = _ModuleType,
                        ModuleBLL = _ModuleBLL,
                        FixType = _FixType,
                        FixTime = _FixTime,
                        IsRun = (_IsRun == 1),
                        IsNotify = (_IsNotify == 1),
                        Remark = _Remark,
                        SortID = _SortID,
                        Status = (int)ServiceStatus.Stop,
                        NextRunTime = null,
                        CreateTime = DateTime.Now
                    };
                    db.ServiceModuleInfo.Add(objData);
                    db.SaveChanges();
                    //添加日志
                    AppLogService.InsertLog<ServiceModuleInfo>(objData, objData.ModuleID.ToString());
                    //返回信息
                    _result.Data = new
                    {
                        result = true,
                        msg = "数据保存成功"
                    };
                }
                catch (Exception ex)
                {
                    _result.Data = new
                    {
                        result = false,
                        msg = ex.Message
                    };
                }
                return _result;
            }
        }
        #endregion

        #region 编辑
        [UserPowerAuthorize]
        public ActionResult Edit()
        {
            //加载语言包
            ViewBag.LanguagePack = this.GetLanguagePack;

OMS.App/Views/ServiceConfig/Add.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="main">
    <div class="main_edit">
        <form id="subform" method="post">
            <table class="table">
                <tbody>
                    <tr>
                        <th>
                            <span class="color_danger">*</span>服务名称：
                        </th>
                        <td>
                            <input name="ModuleTitle" type="text" class="easyui-textbox input-xlarge" />
                        </td>
                    </tr>
                    <tr>
                        <th>
                            <span class="color_danger">*</span>服务工作流ID：
                        </th>
                        <td>
                            <input name="ModuleWorkflowID" type="text" class="easyui-textbox input-xlarge" />
                        </td>
                    </tr>
                    <tr>
                        <th>
                            <span class="color_danger">*</span>服务标识：
                        </th>
                        <td>
                            <input name="ModuleMark" type="text" class="easyui-textbox input-xlarge" />
                        </td>
                    </tr>
                    <tr>
                        <th>
                            <span class="color_danger">*</span>Assembly：
                        </th>
                        <td>
                            <input name="ModuleAssembly" type="text" class="easyui-textbox input-xlarge" />
                        </td>
                    </tr>
                    <tr>
                        <th>
                            <span class="color_danger">*</span>Class：
                        </th>
                        <td>
                            <input name="ModuleType" type="text" class="easyui-textbox input-xlarge" />
                        </td>
                    </tr>
                    <tr>
                        <th>
                            <span class="color_danger">*</span>BLL：
                        </th>
                        <td>
                            <input name="ModuleBLL" type="text" class="easyui-textbox input-xlarge" />
                        </td>
                    </tr>
                    <tr>
                        <th>
                            定时类型：
                        </th>
                        <td>
                            <input id="f1" name="FixType" type="radio" value="1" checked="checked"><label for="f1">间隔执行</label>
                            <input id="f2" name="FixType" type="radio" value="2"><label for="f2">定时执行</label>
                        </td>
                    </tr>
                    <tr>
                        <th>
                            时间：
                        </th>
                        <td>
                            <input name="FixTime" type="text" class="easyui-textbox input-large" />
                            <span class="label-info">*24小时制</span>
                        </td>
                    </tr>
                    <tr>
                        <th>
                            <span class="color_danger">*</span>是否有效：
                        </th>
                        <td>
                            <input id="r_1" name="IsRun" type="radio" value="1" checked="checked"><label for="r_1">是</label>
                            <input id="r_2" name="IsRun" type="radio" value="0"><label for="r_2">否</label>
                        </td>
                    </tr>
                    <tr>
                        <th>
                            <span class="color_danger">*</span>是否错误通知：
                        </th>
                        <td>
                            <input id="n_1" name="IsNotify" type="radio" value="1" checked="checked"><label for="n_1">是</label>
                            <input id="n_2" name="IsNotify" type="radio" value="0"><label for="n_2">否</label>
                        </td>
                    </tr>
                    <tr>
                        <th>
                            简要描述：
                        </th>
                        <td>
                            <textarea name="Remark" class="easyui-textarea  input-xlarge" style="height:100px;"></textarea>
                        </td>
                    </tr>
                </tbody>
            </table>
        </form>
    </div>
</div>

OMS.App/Views/ServiceConfig/Edit.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    var _m = (Samsonite.OMS.Database.ServiceModuleInfo)Model;
}
<div class="main">
    <div class="main_edit">
        <form id="subform" method="post">
            <input name="ID" type="hidden" value="@_m.ModuleID" />
            <table class="table">
                <tbody>
                    <tr>
                        <th>
                            <span class="color_danger">*</span>服务名称：
                        </th>
                        <td>
                            <input name="ModuleTitle" type="text" class="easyui-textbox input-xlarge" value="@_m.ModuleTitle" />
                        </td>
                    </tr>
                    <tr>
                        <th>
                            <span class="color_danger">*</span>服务工作流ID：
                        </th>
                        <td>
                            <input name="ModuleWorkflowID" type="text" class="easyui-textbox input-xlarge" value="@_m.ModuleWorkflowID" />
                        </td>
                    </tr>
                    <tr>
                        <th>
                            <span class="color_danger">*</span>服务标识：
                        </th>
                        <td>
                            <input name="ModuleMark" type="text" class="easyui-textbox input-xlarge" value="@_m.ModuleMark" />
                        </td>
                    </tr>
                    <tr>
                        <th>
                            <span class="color_danger">*</span>Assembly：
                        </th>
                        <td>
                            <input name="ModuleAssembly" type="text" class="easyui-textbox input-xlarge" value="@_m.ModuleAssembly" />
                        </td>
                    </tr>
                    <tr>
                        <th>
                            <span class="color_danger">*</span>Class：
                        </th>
                        <td>
                            <input name="ModuleType" type="text" class="easyui-textbox input-xlarge" value="@_m.ModuleType" />
                        </td>
                    </tr>
                    <tr>
                        <th>
                            <span class="color_danger">*</span>BLL：
                        </th>
                        <td>
                            <input name="ModuleBLL" type="text" class="easyui-textbox input-xlarge" value="@_m.ModuleBLL" />
                        </td>
                    </tr>
                    <tr>
                        <th>
                            定时类型：
                        </th>
                        <td>
                            <input id="f1" name="FixType" type="radio" value="1" @((_m.FixType == 1) ? "checked=\"checked\"" : "")><label for="f1">间隔执行</label>
                            <input id="f2" name="FixType" type="radio" value="2" @((_m.FixType == 2) ? "checked=\"checked\"" : "")><label for="f2">定时执行</label>
                        </td>
                    </tr>
                    <tr>
                        <th>
                            时间：
                        </th>
                        <td>
                            <input name="FixTime" type="text" class="easyui-textbox input-large" value="@_m.FixTime" />
                            <span class="label-info">*24小时制</span>
                        </td>
                    </tr>
                    <tr>
                        <th>
                            <span class="color_danger">*</span>是否有效：
                        </th>
                        <td>
                            <input id="r_1" name="IsRun" type="radio" value="1" @((_m.IsRun) ? "checked=\"checked\"" : "")><label for="r_1">是</label>
                            <input id="r_2" name="IsRun" type="radio" value="0" @((!_m.IsRun) ? "checked=\"checked\"" : "")><label for="r_2">否</label>
                        </td>
                    </tr>
                    <tr>
                        <th>
                            <span class="color_danger">*</span>是否错误通知：
                        </th>
                        <td>
                            <input id="n_1" name="IsNotify" type="radio" value="1" @((_m.IsNotify) ? "checked=\"checked\"" : "")><label for="n_1">是</label>
                            <input id="n_2" name="IsNotify" type="radio" value="0" @((!_m.IsNotify) ? "checked=\"checked\"" : "")><label for="n_2">否</label>
                        </td>
                    </tr>
                    <tr>
                        <th>
                            排序：
                        </th>
                        <td>
                            <input name="Sort" type="text" class="easyui-numberbox input-mini" value="@_m.SortID" data-options="min:0" />
                        </td>
                    </tr>
                    <tr>
                        <th>
                            简要描述：
                        </th>
                        <td>
                            <textarea name="Remark" class="easyui-textarea  input-xlarge" style="height:100px;">@_m.Remark</textarea>
                        </td>
                    </tr>
                </tbody>
            </table>
        </form>
    </div>
</div>

OMS.App/Views/ServiceConfig/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";

    var _ServiceStatusList = (List<object[]>)ViewData["service_status_list"];
    var _ServiceList = (List<Samsonite.OMS.Database.ServiceModuleInfo>)ViewData["service_list"];
    var _JobTypeList = (List<object[]>)ViewData["job_type_list"];
    var _JobStatusList = (List<object[]>)ViewData["job_status_list"];
}
<div class="main">
    <div class="main_top">@Html.Raw(ViewBag.MenuBar)</div>
    <div id="tt" class="easyui-tabs">
        <div class="main_tab" title="服务设置">
            <div class="main_search">
                <ul>
                    <li>
                        <input id="SearchKey" type="text" class="easyui-textbox input-large" prompt="搜索关键字" />
                    </li>
                    <li>
                        运行状态:
                        <select id="Status" class="easyui-combobox">
                            <option value="0">--全部--</option>
                            @foreach (var _o in _ServiceStatusList)
                            {
                                <option value="@(Convert.ToInt32(_o[0])+1)">@_o[1]</option>
                            }
                        </select>
                    </li>
                    <li>
                        是否有效:
                        <input id="IsRun" type="checkbox" value="1" />
                    </li>
                    <li>
                        <input id="SearchButton" type="button" value="查询" class="btn btn-info" />
                    </li>
                    <li>
                        <span class="label-danger">*创建新服务或者完全关闭服务线程需要重启服务才能有效</span>
                    </li>
                </ul>
            </div>
            <div class="main_list">
                <div id="toolbar">
                    <a id="add" href="javascript:void(0)" class="easyui-linkbutton" plain="true"><i class="fa fa-plus color_success"></i>添加</a>
                    <a id="edit" href="javascript:void(0)" class="easyui-linkbutton" plain="true"><i class="fa fa-pencil-square-o color_warning"></i>编辑</a>
                    <span class="toolbar-separator"></span>
                    <a id="refresh" href="javascript:void(0)" class="easyui-linkbutton" plain="true" power="false"><i class="fa fa-refresh color_info"></i>刷新</a>
                </div>
                <table id="dg">
                    <thead>
                        <tr>
                            <th data-options="field:'ck',checkbox:true">
                            </th>
                            <th data-options="field:'s1',align:'left'">
                                服务名称
                            </th>
                            <th data-options="field:'s2',align:'left'">
                                服务标识
                            </th>
                            <th data-options="field:'s3',align:'left'">
                                Class
                            </th>
                            <th data-options="field:'s4',align:'left'">
                                执行方式
                            </th>
                            <th data-options="field:'s5',align:'center'">
                                排序
                            </th>
                            <th data-options="field:'s6',align:'center'">
                                开启状态
                            </th>
                            <th data-options="field:'s7',align:'center'">
                                操作
                            </th>
                            <th data-options="field:'s8',align:'left'">
                                下次执行时间
                            </th>
                            <th data-options="field:'s9',align:'center'">
                                有效
                            </th>
                            <th data-options="field:'s10',align:'center'">
                                是否错误通知
                            </th>
                            <th data-options="field:'s11',align:'left'">
                                备注
                            </th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
        <div class="main_tab" title="操作日志">
            <div class="main_search">
                <ul>
                    <li>
                        服务列表:
                        <select id="ModuleID" class="easyui-combobox">
                            <option value="0">--全部--</option>
                            @{
                                foreach (var _o in _ServiceList)
                                {
                                    <option value="@_o.ModuleID">@_o.ModuleTitle</option>
                                }
                            }
                        </select>
                    </li>
                    <li>
                        操作类型:
                        <select id="JobType" class="easyui-combobox">
                            <option value="0">--全部--</option>
                            @foreach (var _o in _JobTypeList)
                            {
                                <option value="@_o[0]">@_o[1]</option>
                            }
                        </select>
                    </li>
                    <li>
                        操作状态:
                        <select id="JobStatus" class="easyui-combobox">
                            <option value="0">--全部--</option>
                            @foreach (var _o in _JobStatusList)
                            {
                                <option value="@(Convert.ToInt32(_o[0])+1)">@_o[1]</option>
                            }
                        </select>
                    </li>
                    <li>
                        日期:
                        <input id="SearchTime" type="text" class="input-medium Wdate" onclick="WdatePicker({dateFmt:'yyyy-MM-dd'})" />
                    </li>
                    <li>
                        <input id="SearchButton1" type="button" value="查询" class="btn btn-info" />
                    </li>
                </ul>
            </div>
            <div class="main_list">
                <div id="toolbar1">
                    <a id="refresh1" href="javascript:void(0)" class="easyui-linkbutton" plain="true" power="false"><i class="fa fa-refresh color_info"></i>刷新</a>
                </div>
                <table id="dg1">
                    <thead>
                        <tr>
                            <th data-options="field:'s1',align:'left'">
                                服务名称
                            </th>
                            <th data-options="field:'s2',align:'left'">
                                操作类型
                            </th>
                            <th data-options="field:'s3',align:'left'">
                                状态
                            </th>
                            <th data-options="field:'s4',align:'left'">
                                状态信息
                            </th>
                            <th data-options="field:'s5',align:'left'">
                                添加时间
                            </th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>
@section scripts {
    @Scripts.Render("~/Content/js-library/my97datepicker/4.7.2/WdatePicker.js")
    <script type="text/javascript">
        $(function () {
            //----------------------服务设置---------------------------------
            //工具栏
            easyUIExtend.Grid.Toolbar($('#toolbar'), {
                powerTools: ('@ViewBag.FunctionPower').split(',')
            });
            //列表
            easyUIExtend.Grid.List($('#dg'), {
                toolbar: '#toolbar',
                url: '@Url.Action("Index_Message","ServiceConfig")',
                pageSize: 20
            });
            //搜索
            $('#SearchButton').bind('click', function () {
                easyUIExtend.Grid.Search($('#dg'), {
                    keyword: $('#SearchKey').val(),
                    status: $('#Status').combobox('getValue'),
                    isrun: $('#IsRun').prop("checked") ? 1 : 0
                });
            });
            //操作
            $('#toolbar').find('#add').bind('click', function () {
                easyUIExtend.Grid.SaveDialog({
                    url: '@Url.Action("Add", "ServiceConfig")',
                    title: '添加信息',
                    width: '100%',
                    height: '100%',
                    dataUrl: '@Url.Action("Add_Message", "ServiceConfig")'
                });
            });
            $('#toolbar').find('#edit').bind('click', function () {
                easyUIExtend.Grid.SaveOper($('#dg'), {
                    url: '@Url.Action("Edit", "ServiceConfig")?id=$',
                    title: '编辑信息',
                    width: '100%',
                    height: '100%',
                    dataUrl: '@Url.Action("Edit_Message", "ServiceConfig")'
                });
            });
            $('#toolbar').find('#refresh').bind('click', function () {
                easyUIExtend.Grid.Refresh($('#dg'));
            });

            //----------------------操作日志---------------------------------
            //列表
            easyUIExtend.Grid.List($('#dg1'), {
                toolbar: '#toolbar1',
                url: '@Url.Action("Index_OperLog_Message","ServiceConfig")',
                pageSize: 20
            });
            //搜索
            $('#SearchButton1').bind('click', function () {
                easyUIExtend.Grid.Search($('#dg1'), {
                    moduleid: $('#ModuleID').combobox('getValue'),
                    job_type: $('#JobType').combobox('getValue'),
                    job_status: $('#JobStatus').combobox('getValue'),
                    time: $('#SearchTime').val(),
                });
            });
            //操作
            $('#toolbar1').find('#refresh1').bind('click', function () {
                easyUIExtend.Grid.Refresh($('#dg1'));
            });
        });

        function startService(id) {
            operService(id, @Convert.ToInt32(Samsonite.OMS.DTO.JobType.Start));
        }

        function pauseService(id) {
            operService(id, @Convert.ToInt32(Samsonite.OMS.DTO.JobType.Pause));
        }

        function continueService(id) {
            operService(id, @Convert.ToInt32(Samsonite.OMS.DTO.JobType.Continue));
        }

        function operService(id, type) {
            artDialogExtend.Confirm('确实进行该操作?', function () {
                commonJs.sysAjaxFunction({
                    url: '@Url.Action("Oper_Message", "ServiceConfig")',
                    dataType: 'json',
                    para: {
                        id: id,
                        type:type
                    },
                    func: function (data) {
                        if (data.result) {
                            artDialogExtend.Tips.Success(data.msg, 3, function () {
                                easyUIExtend.Grid.Refresh($('#dg'));
                            });
                        }
                        else {
                            artDialogExtend.Tips.Alert(data.msg, 5);
                        }
                    }
                });
            }, function () { return true });
        }
    </script>
}